### ISSUE TITLE
Rsk3.js: revert #558 when estimateGas and getTransactionCount are fixed in rsk3.js

### ISSUE THREAD

**Issue by chrisli30** [rsksmart/rwallet#561]
Due to a problem where rsk3.js estimate and getTransactionCount methods throw error on checksum address input, we have to work around to make address all lower case before calling those functions. When the issue is fixed we can revert the PR linked in the issue.

Related Rsk3.js Issue
https://github.com/rsksmart/rsk3.js/issues/66

Related RWallet PR
https://github.com/rsksmart/rwallet/pull/558

**Comment by AmazingBeerBelly** [comment]
```
const Web3 = require('web3');
const Rsk3 = require('@rsksmart/rsk3')

const web3 = new Web3('https://public-node.testnet.rsk.co');
const rsk3 = new Rsk3('https://public-node.testnet.rsk.co');

const address = '0xE62278ac258BDA2aE6E8eCA32D01d4Cb3b631257';
const networkId = 30;

const web3ChecksumAddress = Web3.utils.toChecksumAddress(address, networkId);
const rsk3ChecksumAddress = Rsk3.utils.toChecksumAddress(address, networkId);

const main = async () => {
  console.log('-------- Web3 -------');
  console.log('web3ChecksumAddress: ', web3ChecksumAddress);
  await web3.eth.estimateGas({
    from: web3ChecksumAddress,
    to: web3ChecksumAddress,
    value: '0x0',
  }).then(res => {
    console.log('web3 res: ', res);
  }).catch(error => {
    console.log('web3 error: ', error);
  })

  console.log('-------- Rsk3 -------');

  console.log('rsk3ChecksumAddress: ', rsk3ChecksumAddress);
  await rsk3.estimateGas({
    from: rsk3ChecksumAddress,
    to: rsk3ChecksumAddress,
    value: '0x0',
  }).then(res => {
    console.log('rsk3 res: ', res);
  }).catch(error => {
    console.log('rsk3 error: ', error);
  })
}

main();
```

```
-------- Web3 -------
web3ChecksumAddress:  0xe62278ac258bda2ae6e8EcA32d01d4cB3B631257
web3 res:  21000
-------- Rsk3 -------
rsk3ChecksumAddress:  0xE62278ac258BDA2aE6E8eCA32D01d4Cb3b631257
rsk3 error:  Error: Provided address "0xE62278ac258BDA2aE6E8eCA32D01d4Cb3b631257" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
    at inputAddressFormatter (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@rsksmart/rsk3/node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:259:9)
    at txInputFormatter (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@rsksmart/rsk3/node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:40:19)
    at Object.inputCallFormatter (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@rsksmart/rsk3/node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:63:14)
    at EstimateGasMethod.beforeExecution (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-method/dist/web3-core-method.cjs.js:1492:44)
    at EstimateGasMethod._callee$ (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-method/dist/web3-core-method.cjs.js:88:22)
    at tryCatch (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at EstimateGasMethod.<anonymous> (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at EstimateGasMethod.execute (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-method/dist/web3-core-method.cjs.js:138:25)
    at Proxy.RpcMethod (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-method/dist/web3-core-method.cjs.js:599:25)
    at main (/Users/shizhongwei/app/project/contract/rnsDemo/estimate.js:29:14)
```
